-- R1
DROP TABLE IF EXISTS R1ABD;
DROP TABLE IF EXISTS R1BC;
DROP TABLE IF EXISTS R1DE;
CREATE TABLE R1BC (
     B CHAR(10),
     C CHAR(1),
     PRIMARY KEY (B)
);
CREATE TABLE R1DE (
     D INT,
     E VARCHAR(30),
     PRIMARY KEY (D)
);
CREATE TABLE R1ABD (
     A INT,
     B CHAR(10),
     D INT,
     PRIMARY KEY (A),
     FOREIGN KEY (B) REFERENCES R1BC(B),
     FOREIGN KEY (D) REFERENCES R1DE(D)
);


-- R2
DROP TABLE IF EXISTS R2ABCE;
DROP TABLE IF EXISTS R2AD;
CREATE TABLE R2AD (
     A INT,
     D INT,
     PRIMARY KEY (A)
);
CREATE TABLE R2ABCE (
     A INT,
     B CHAR(10),
     C CHAR(1),
     E VARCHAR(30),
     PRIMARY KEY (A, B, C)
);


-- R3
DROP TABLE IF EXISTS R3ABCD;
DROP TABLE IF EXISTS R3DE;
CREATE TABLE R3DE (
     D INT,
     E VARCHAR(30),
     PRIMARY KEY (D)
);
CREATE TABLE R3ABCD (
     A INT,
     B CHAR(10),
     C CHAR(1),
     D INT,
     PRIMARY KEY (A, B)
);


-- R4
DROP TABLE IF EXISTS R4AB;
DROP TABLE IF EXISTS R4AD;
DROP TABLE IF EXISTS R4EC;
DROP TABLE IF EXISTS R4AE;
CREATE TABLE R4AB (
     A INT,
     B CHAR(10),
     PRIMARY KEY (A, B)
);
CREATE TABLE R4AD (
     A INT,
     D INT,
     PRIMARY KEY (A, D)
);
CREATE TABLE R4EC (
     E VARCHAR(30),
     C CHAR(1),
     PRIMARY KEY (E)
);
CREATE TABLE R4AE (
     A INT,
     E VARCHAR(30),
     PRIMARY KEY (A)
);