-- R1

INSERT INTO R1BC SELECT DISTINCT B, C FROM R1;
INSERT INTO R1DE SELECT DISTINCT D, E FROM R1;
INSERT INTO R1ABD SELECT DISTINCT A, B, D FROM R1;

SELECT ORG.N - NEW.N AS DIFF_COUNT, ORG.S - NEW.S AS DIFF_SUM
FROM (SELECT COUNT(*) AS N, SUM(DE.D) AS S
      FROM R1ABD ABD, R1BC BC, R1DE DE
      WHERE ABD.B = BC.B AND ABD.D = DE.D) NEW,
     (SELECT COUNT(*) AS N, SUM(D) AS S
      FROM R1) ORG;

-- R2

INSERT INTO R2AD SELECT DISTINCT A, D FROM R2;
INSERT INTO R2ABCE SELECT DISTINCT A, B, C, E FROM R2;

SELECT ORG.N - NEW.N AS DIFF_COUNT, ORG.S - NEW.S AS DIFF_SUM
FROM (SELECT COUNT(*) AS N, SUM(AD.D) AS S
      FROM R2ABCE ABCE, R2AD AD
      WHERE ABCE.A = AD.A) NEW,
     (SELECT COUNT(*) AS N, SUM(D) AS S
      FROM R2) ORG;

-- R3

INSERT INTO R3DE SELECT DISTINCT D, E FROM R3;
INSERT INTO R3ABCD SELECT DISTINCT A, B, C, D FROM R3;

SELECT ORG.N - NEW.N AS DIFF_COUNT, ORG.S - NEW.S AS DIFF_SUM
FROM (SELECT COUNT(*) AS N, SUM(DE.D) AS S
      FROM R3ABCD ABCD, R3DE DE
      WHERE ABCD.D = DE.D) NEW,
     (SELECT COUNT(*) AS N, SUM(D) AS S
      FROM R3) ORG;

-- R4

INSERT INTO R4AB SELECT DISTINCT A, B FROM R4;
INSERT INTO R4AD SELECT DISTINCT A, D FROM R4;
INSERT INTO R4EC SELECT DISTINCT E, C FROM R4;
INSERT INTO R4AE SELECT DISTINCT A, E FROM R4;

SELECT ORG.N - NEW.N AS DIFF_COUNT, ORG.S - NEW.S AS DIFF_SUM
FROM (SELECT COUNT(*) AS N, SUM(AD.D) AS S
      FROM R4AB AB, R4AD AD, R4EC EC, R4AE AE
      WHERE AB.A = AD.A AND AB.A = AE.A AND AE.E = EC.E) NEW,
     (SELECT COUNT(*) AS N, SUM(D) AS S
      FROM R4) ORG;
